current_dir=~/.config/zsh
echo $current_dir
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/rpendergraph/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="afowler"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(vi-mode zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh



# Aliases
source $current_dir/aliases.zsh

GIT_PS1_SHOWDIRTYSTATE=true

# Git completion 
if [ ! -f $current_dir/git-completion.bash ]; then
   curl -o $current_dir/git-completion.bash https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
   curl -o $current_dir/_git https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh
fi
zstyle ':completion:*:*:git:*' script $current_dir/git-completion.bash
fpath=($current_dir $fpath)
autoload -Uz compinit && compinit
# End Git completion

source ~/.kubernetes-functions-bash

export EDITOR='nvim'
export TERM=xterm-256color
export PATH=/usr/local/bin/:$PATH:~/go/bin
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=18'
export KUBECONFIG=~/.config.k8s-pddev.rpendergraph
export TILLER_NAMESPACE=rpendergraph
export GOPROXY="http://rpendergraph:AKCp5ccbCEJEC4khr8yx9gVAmEGiK9UTGixtQkWBaytXRmFp8MnFrJT5VT9EL4T44yUY27LSL@artifactory.dev.circadence.net/artifactory/api/go/go"

alias code="/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron"

if [ $ITERM_SESSION_ID ]; then
  export PROMPT_COMMAND='echo -ne "\033];${PWD##*/}\007"; ':"$PROMPT_COMMAND";
fi

#[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
